[project]
name = "cpp_project_guideline"
version = "0.1.0"
description = "C++ project guidelines"
authors = ["jiaxiyang <jiaxiyangbit@126.com>"]
channels = ["conda-forge", "bioconda", "nvidia", "pytorch"]
platforms = ["linux-64"]

[activation]
scripts = ["scripts/env_setup.sh"]

[tasks]
install = { cmd = "npm i cfonts -g && cfonts 'install'" }
format_check = { cmd = "cfonts 'format' && ./scripts/run-clang-format.py -r samples" }
cpplint = { cmd = "cfonts 'cpplint' && cpplint include/* src/* samples/*" }
base = { cmd = "cfonts 'examples' && bash -ex scripts/build.sh -DCMAKE_CXX_FLAGS=\"-g -Wall -Wextra -Werror\"" }
perf = { cmd = "cfonts 'perf' && bash -ex ./scripts/perf_flamegraph.sh ./build/samples/base", depends_on = [ "base" ] }
gtest = { cmd = "cfonts 'gtest' && ctest -VV --test-dir build", depends_on = [ "base" ] }
asan-mem = { cmd = "cfonts 'asan mem' && bash -ex scripts/build.sh -DCMAKE_CXX_FLAGS=\"-fsanitize=address -g -lasan\" && ./build/samples/base" }
asan-thread = { cmd = "cfonts 'asan thread' && bash -ex scripts/build.sh -DCMAKE_CXX_FLAGS=\"-fsanitize=thread -g -static-libasan\" && ./build/samples/base" }
valgrind = { cmd = "cfonts 'valgrind' && bash -ex scripts/build.sh -DCMAKE_CXX_FLAGS=\"-g\" && valgrind --leak-check=full ./build/samples/base" }
gcovr = { cmd = "cfonts 'gcovr' && bash -ex scripts/build.sh -DCMAKE_CXX_FLAGS=\"--coverage -g -O0\" && ctest -VV --test-dir build && mkdir -p gcovr && gcovr --gcov-ignore-parse-errors" }
clang-tidy = { cmd = "cfonts 'tidy' && run-clang-tidy -p build/ -quiet -use-color", depends_on = [ "base" ] } # after build
doxygen = { cmd = "cfonts 'doxygen' && doxygen doc/Doxyfile.in " }
all = { cmd = "pwd", depends_on = [
            "install",
            "format_check",
            "cpplint",
            "base",
            "clang-tidy",
            # "perf",
            "gtest",
            "asan-mem",
            "asan-thread",
            "valgrind",
            "gcovr",
            "doxygen"
        ]}

[dependencies]
cmake = "3.27.6.*"
glog = "0.6.0.*"
ninja = "1.11.1.*"
eigen = "3.4.0.*"
gcc = "13.2.0.*"
gxx = "13.2.0.*"
clang = "17.0.4.*"
clangxx = "17.0.4.*"
clang-format = "17.0.4.*"
nodejs = "20.9.0.*"
cpplint = "1.6.0.*"
python = ">3.9,<=3.11"
clang-tools = "17.0.4.*"
gcovr = "5.2.*"
gprof2dot = "2019.11.30.*"
linux-perf = "6.3.10.*"
valgrind = "3.22.0.*"
gtest = "1.14.0.*"
doxygen = "1.9.8.*"
