name: CI
on: push

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  project-test:
    name: project test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.3.0
    - name: install deps
      run: sudo  apt-get update && sudo apt-get install -y libc6-dbg linux-tools-common linux-tools-$(uname -r)
      # run: sudo  apt-get update && sudo apt-get install -y libc6-dbg linux-tools-generic && sudo rm /usr/bin/perf && sudo ln -s /usr/lib/linux-tools/5.15.0-89-generic/perf /usr/bin/perf
    - name: run
      run: pixi run all
    # - name: test summary
    #   uses: test-summary/action@v2
    #   with:
    #     paths: "build/test/*.xml"
    - name: test report
      uses: dorny/test-reporter@v1
      with:
        name: unit test
        path: "build/test/*.xml"
        reporter: jest-junit
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ github.sha }}
        path: |
          gcovr
          build/test/report.xml
          doc_html
