name: Ubuntu
on: push

jobs:
  project-test:
    name: project test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.3.0
    - name: install deps
      run: apt install -y libc6-dbg
    - name: run
      run: pixi run all
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: gcovr
